---
version: 4.1.0
name: Blog
description: Blog
repository: https://github.com/YTKme/Blog
timezone: America/Los_Angeles

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/posts/:year/:month/:day/:title/"
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: posts

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

feed:
  categories:
    - release

sass:
  style: compressed

strict_front_matter: true

exclude:
  - .gitignore
  - bootstrap